fresh_shop/cart/urls.py
from django.urls import path

from cart import views


urlpatterns = [
    # 加入购物车
    path('add_cart/', views.add_cart, name='add_cart'),
    # 购物车数量的刷新
    path('cart_num/', views.cart_num, name='cart_num'),
    # 购物车
    path('cart/', views.cart, name='cart'),
    # 购物车计算价格
    path('cart_price/', views.cart_price, name='cart_price'),
    # 修改购物车中的数量/选择状态
    path('change_cart/', views.change_cart, name='change_cart'),
    # 删除购物车中的商品
    path('del_cart_goods/', views.del_cart_goods, name='del_cart_goods'),
]

fresh_shop/fresh_shop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from goods import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 导入应用
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('goods/', include(('goods.urls', 'goods'), namespace='goods')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    # 首页路径
    path('', views.index)
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fresh_shop/goods/urls.py
from django.urls import path

from goods import views


urlpatterns = [
    # 首页
    path('index/', views.index, name='index'),
    # 详情
    path('detail/<int:id>/', views.detail, name='detail'),
    # 商品列表页
    path('list/', views.list, name='list'),
]

fresh_shop/order/urls.py
from django.urls import path

from order import views


urlpatterns = [
    # 结算功能
    path('place_order/', views.place_order, name='place_order'),
    # 创建订单
    path('order/', views.order, name='order'),
    # 全部订单
    path('user_order/', views.user_order, name='user_order'),
]

fresh_shop/user/urls.py
from django.urls import path

from user import views


urlpatterns = [
    # 注册
    path('register/', views.register, name='register'),
    # 登录
    path('login/', views.login, name='login'),
    # 退出
    path('logout/', views.logout, name='logout'),
    # 收货地址
    path('user_site/', views.user_site, name='user_site'),
    # 个人中心
    path('user_info/', views.user_info, name='user_info'),
]

fresh_shop/cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

fresh_shop/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

from cart.models import ShoppingCart
from goods.models import Goods


def add_cart(request):
    if request.method == 'POST':
        # 接收商品id值和商品数量num
        # 组装存储的商品格式：[goods_id, num, is_select]
        # 组装多个商品格式：[[goods_id, num, is_select], [goods_id, num, is_select] ...]
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        # 组装存的数据
        good_list = [goods_id, goods_num, 1]
        session_goods = request.session.get('goods')
        if session_goods:
            # 1、如果添加重复的商品，则修改
            flag = True
            for se_goods in session_goods:
                if se_goods[0] == goods_id:
                    se_goods[1] += goods_num
                    flag = False
            if flag:
                # 2、如果添加的商品不存在于购物车中，则新增
                session_goods.append(good_list)
            request.session['goods'] = session_goods
            count = len(session_goods)
        else:
            # 表示第一次添加购物车
            # 需组装购物车中商品格式为[[goods_id, num, is_select]...]
            request.session['goods'] = [good_list]
            count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart_num(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        count = len(session_goods) if session_goods else 0
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 组装返回格式：[objects1, object2 ...]
        # objects ===> [Goods Object, is_select, num, total_price]
        result = []
        for se_goods in session_goods:
            # se_goods为[goods_id, num, is_select]
            goods = Goods.objects.filter(pk=se_goods[0]).first()
            total_price = goods.shop_price * se_goods[1]
            data = [goods, se_goods[1], se_goods[2], total_price]
            result.append(data)
        return render(request, 'cart.html', {'result': result})


def cart_price(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 总的商品件数
        all_total = len(session_goods) if session_goods else 0
        all_price = 0
        is_select_num = 0
        for se_goods in session_goods:
            if se_goods[2]:
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                all_price += goods.shop_price * se_goods[1]
                is_select_num += 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'all_total': all_total, 'all_price': all_price,
                             'is_select_num': is_select_num})


def change_cart(request):
    if request.method == 'POST':
        # 修改商品的数量和选择状态
        # 其实就是修改session中商品信息，结构为[goods_id, num, is_select]

        # 1、获取商品id值和（数量或选择状态）
        goods_id = int(request.POST.get('goods_id'))
        goods_num = request.POST.get('goods_num')
        goods_select = request.POST.get('goods_select')

        # 2、修改
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == goods_id:
                se_goods[1] = int(goods_num) if goods_num else se_goods[1]
                se_goods[2] = int(goods_select) if goods_select else se_goods[2]
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功'})


def del_cart_goods(request):
    if request.method == 'POST':
        goods_id = int(request.POST.get('goods_id'))
        session_goods = request.session.get('goods')
        for index in range(len(session_goods)):
            # se_good结构为[goods_id, num, is_select]
            if session_goods[index][0] == goods_id:
                del session_goods[index]
                break
        request.session['goods'] = session_goods
        # 删除数据库，购物车中的商品信息
        user_id = request.session.get('user_id')
        if user_id:
            ShoppingCart.objects.filter(goods_id=goods_id, user_id=user_id).delete()
        return JsonResponse({'code': 200, 'msg': '请求成功'})

fresh_shop/templates/base_main.html
{% extends 'base.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock %}

{% block js1 %}
    {% load static %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock %}

{% block header %}
    <div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl" {% if user.id %} style="display: block" {% endif %}>
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
				<div class="login_btn fl"{% if user.id %} style="display: none" {% endif %}>
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'order:user_order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

{% block search %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
        <script>
            function refresh_cart_num(){
                $.get('/cart/cart_num/', function (data) {
                    if(data.code == '200'){
                        $('#show_count').text(data.count)
                    }
                })
            }
            refresh_cart_num()
        </script>
	</div>
{% endblock %}

{% block footer %}
    <div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock %}

fresh_shop/templates/base_user.html
 <ul>
    <li><a href="{% url 'user:user_info' %}" {% if activate == 'info' %}class="active"{% endif %}>· 个人信息</a></li>
    <li><a href="{% url 'order:user_order' %}" {% if activate == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
    <li><a href="{% url 'user:user_site' %}" {% if activate == 'site' %}class="active"{% endif %}>· 收货地址</a></li>
</ul>

fresh_shop/templates/detail.html
{% extends 'base_main.html' %}


{% block title %}
    天天生鲜-商品详情
{% endblock %}


{% block content %}
    <div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					<li><a href="{% url 'goods:list' %}?genre=1" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goods:list' %}?genre=2" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goods:list' %}?genre=3" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goods:list' %}?genre=4" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goods:list' %}?genre=5" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goods:list' %}?genre=6" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:list' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'goods:list' %}?genre={{ types.1 }}">{{ types.0 }}</a>
		<span>></span>
		<a href="#">商品详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl">
            <img src="/media/{{ goods.goods_front_image }}"></div>
		<div class="goods_detail_list fr">
			<h3>{{ goods.name }}</h3>
			<p>{{ goods.goods_brief }}</p>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ goods.shop_price }}</em></span>
				<span class="show_unit">单  位：500g</span>
                <span class="show_unit">浏览量：{{ goods.click_nums }}</span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr" onclick="add_goods()">+</a>
					<a href="javascript:;" class="minus fr" onclick="sub_goods()">-</a>
				</div>
                <script>
                    {# 加商品 #}
                    function add_goods() {
                        var num = $('.num_show').val()
                        var new_num = parseInt(num) + 1
                        $('.num_show').val(new_num)
                    }
                    {# 减商品 #}
                    function sub_goods() {
                        var num = $('.num_show').val()
                        if (parseInt(num) > 1){
                            var new_num = parseInt(num) - 1
                            $('.num_show').val(new_num)
                        }
                    }
                </script>
			</div>
			<div class="total">总价：<em>{{ goods.shop_price }}元</em></div>
			<div class="operate_btn">
				<a href="javascript:;" class="buy_btn">立即购买</a>
				<a href="javascript:;" class="add_cart" id="add_cart" onclick="add_cart({{ goods.id }})">加入购物车</a>
			</div>
            {% csrf_token %}
            <script>
                function add_cart(id) {
                    var num = $('.num_show').val()
                    var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                    $.ajax({
                        url: '/cart/add_cart/',
                        type: 'POST',
                        data: {'goods_id': id, 'goods_num': num},
                        headers: {'X-CSRFToken': csrf},
                        dataType: 'json',
                        success: function (data) {
                            if(data.code == '200'){
                                $('#show_count').text(data.count)
                                console.log(data.count)
                            }
                        },
                        error: function (data) {
                            console.log('失败')
                        }
                    })
                }
            </script>
		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<ul class="detail_tab clearfix">
				<li class="active">商品介绍</li>
				<li>评论</li>
			</ul>

			<div class="tab_content">
				<dl>
					<dt>商品详情：</dt>
					<dd>{{ goods.goods_desc | safe }}</dd>
				</dl>
			</div>

		</div>
	</div>
{% endblock %}


{% block footer %}
    {{ block.super }}
    <div class="add_jump"></div>
{% endblock %}


{% block js2 %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;

		$(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
		$('#add_cart').click(function(){
			$(".add_jump").stop().animate({
				'left': $to_y+7,
				'top': $to_x+7},
				"fast", function(){
					$(".add_jump").fadeOut('fast',function(){
						{#$('#show_count').html(2);#}
					});

			});
		})
	</script>
{% endblock %}

fresh_shop/templates/list.html
{% extends 'base_main.html' %}


{% block title %}
    天天生鲜-商品列表
{% endblock %}


{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					<li><a href="{% url 'goods:list' %}?genre=1" class="fruit">新鲜水果</a></li>
					<li><a href="{% url 'goods:list' %}?genre=2" class="seafood">海鲜水产</a></li>
					<li><a href="{% url 'goods:list' %}?genre=3" class="meet">猪牛羊肉</a></li>
					<li><a href="{% url 'goods:list' %}?genre=4" class="egg">禽类蛋品</a></li>
					<li><a href="{% url 'goods:list' %}?genre=5" class="vegetables">新鲜蔬菜</a></li>
					<li><a href="{% url 'goods:list' %}?genre=6" class="ice">速冻食品</a></li>
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:list' %}">全部分类</a>
        {% if types %}
            <span>></span>
            <a href="{% url 'goods:list' %}?genre={{ types.1 }}">{{ types.0 }}</a>
        {% endif %}
	</div>
	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for new in news %}
                        <li>
                            <a href="{% url 'goods:detail' new.id %}"><img src="/media/{{ new.goods_front_image }}"></a>
                            <h4><a href="{% url 'goods:detail' new.id %}">{{ new.name }}</a></h4>
                            <div class="prize">￥{{ new.shop_price }}</div>
                        </li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for good in goods %}
                    <li>
					<a href="{% url 'goods:detail' good.id %}"><img src="/media/{{ good.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' good.id %}">{{ good.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ good.shop_price }}</span>
						<span class="unit">{{ good.shop_price }}/500g</span>
						<a href="" class="add_goods" title="加入购物车" onclick="add_cart({{ good.id }})"></a>
					</div>
				</li>
                {% endfor %}
                {% csrf_token %}
                <script>
                    function add_cart(id) {
                        var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                        $.ajax({
                            url: '/cart/add_cart/',
                            type: 'POST',
                            data: {'goods_id': id, 'goods_num': 1},
                            headers: {'X-CSRFToken': csrf},
                            dataType: 'json',
                            success: function (data) {
                                if(data.code == '200'){
                                    {#$('#show_count').text(data.count)#}
                                    console.log(data.count)
                                }
                            },
                            error: function (data) {
                                console.log('失败')
                            }
                        })
                    }
                </script>
			</ul>
			<div class="pagenation">
				<a {% if not goods.has_previous %}class="disabled"{% endif %} {% if goods.has_previous %}href="{% url 'goods:list' %}?page={{ goods.previous_page_number }}"{% endif %}><上一页</a>
                {% for i in goods.paginator.page_range %}
                    <a href="{% url 'goods:list' %}?page={{ i }}" {% if i == goods.number %}class="active"{% endif %}>{{ i }}</a>
                {% endfor %}
				<a {% if not goods.has_next %}class="disabled"{% endif %} {% if goods.has_next %}href="{% url 'goods:list' %}?page={{ goods.next_page_number }}"{% endif %}>下一页></a>
			</div>
		</div>
	</div>
{% endblock %}

fresh_shop/templates/login.html
{% extends 'base_main.html' %}

{% block title %}
    天天生鲜-登录
{% endblock %}

{% block header %}
{% endblock %}

{% block search %}
{% endblock %}


{% block content %}
    <div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error" style="display: block;">{{ errors.username }}</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error" style="display: block;">{{ errors.pwd }}</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="">
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock %}



fresh_shop/templates/place_order.html
{% extends 'base_main.html' %}


{% block title %}
    天天生鲜-提交订单
{% endblock %}


{% block search %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;提交订单</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}


{% block content %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for address in user_address %}
                <dd><input type="radio" name="address_radio" value="{{ address.id }}">{{ address.address }} （{{ address.signer_name }} 收） {{ address.signer_mobile }}</dd>
            {% endfor %}
		</dl>
		<a href="{% url 'user:user_site' %}" class="edit_site">编辑收货地址</a>
	</div>
	
	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for cart in carts %}
            <ul class="goods_list_td clearfix">
                <li class="col01">{{ forloop.counter }}</li>
                <li class="col02"><img src="/media/{{ cart.goods.goods_front_image }}"></li>
                <li class="col03">{{ cart.goods.name }}</li>
                <li class="col04">500g</li>
                <li class="col05">{{ cart.goods.shop_price }}元</li>
                <li class="col06">{{ cart.num }}</li>
                <li class="col07">{{ cart.goods_price }}元</li>
            </ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>2</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>10元</b></div>
			<div class="total_pay">实付款：<b>{{ total_price | add:'10' }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">提交订单</a>
	</div>
{% endblock %}


{% block footer %}
    {{ block.super }}
    <div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>
{% endblock %}


{% block js2 %}
    {% csrf_token %}
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
			localStorage.setItem('order_finish', 2);

            {# 判断是否选择收货地址 #}
            var address_radio = $('input[name="address_radio"]')
            for(var i=0; i<address_radio.length; i++){
                if(address_radio[i].checked == true){
                    var ad_id = address_radio[i].value;
                }
            }
            if(ad_id){
                {# 创建订单 #}
                var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                $.ajax({
                    url: '/order/order/',
                    type: 'POST',
                    dataType: 'json',
                    data: {'ad_id': ad_id},
                    headers: {'X-CSRFToken': csrf},
                    success: function (data) {
                        $('.popup p').text('提交订单成功')
                        $('.popup_con').fadeIn('fast', function() {
                            setTimeout(function(){
                                $('.popup_con').fadeOut('fast',function(){
                                    window.location.href = '{% url "goods:index" %}';
                                });
                            },3000)
                        });
                    },
                    error: function (data) {
                        $('.popup p').text('提交订单失败')
                    }
                })
            }else{
                {# 修改弹窗信息->提交订单失败(请选择收货地址) #}
                $('.popup p').text('提交订单失败(请选择收货地址)')
                $('.popup_con').fadeIn('fast', function() {
                    setTimeout(function(){
                        $('.popup_con').fadeOut('fast',function(){
                            {#window.location.href = 'index.html';#}
                        });
                    },3000)

                });
            }
		});
	</script>
{% endblock %}


fresh_shop/templates/user_center_site.html
{% extends 'base_main.html' %}


{% block title %}
    天天生鲜-用户中心
{% endblock %}


{% block search %}
    <div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
    </div>
{% endblock %}


{% block content %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			{% include 'base_user.html' %}
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% for address in user_address %}
                            <dd>{{ address.address }} ({{ address.signer_name }} 收) {{ address.signer_mobile }}</dd>
                        {% endfor %}
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
                            {{ errors.username }}
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
                            {{ errors.address }}
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="postcode">
                            {{ errors.postcode }}
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="mobile">
                            {{ errors.mobile }}
						</div>

						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock %}